# Hyprland plugins, installed through Nix: hyprpm can't build them on NixOS.
# nixpkgs builds each plugin against the same Hyprland as programs.hyprland,
# so versions always match. hyprland.lua itself stays hand/hyprmod-edited; it
# only needs `require("hyprtasking")` to pick up this file.
{ pkgs, ... }:

{
  xdg.configFile."hypr/hyprtasking.lua".text = ''
    -- Generated by Home Manager (home/hyprland.nix); edit it there.
    -- Niri-style overview: workspaces stacked in one zoomed-out column.
    hl.plugin.load("${pkgs.hyprlandPlugins.hyprtasking}/lib/libhyprtasking.so")

    local function ht()
      return hl.plugin.hyprtasking
    end

    -- While the overview is open, the "overview" submap hands the arrows,
    -- Enter, and Escape to it; the rest of the time they reach apps as usual.
    -- The timer below keeps the submap in sync however the overview opens or
    -- closes (keys, right-click, touchpad gesture).
    local function sync_submap()
      local plugin = ht()
      if plugin == nil then
        return
      end
      local active = plugin.is_active()
      local in_submap = hl.get_current_submap() == "overview"
      if active and not in_submap then
        hl.dispatch(hl.dsp.submap("overview"))
      elseif not active and in_submap then
        hl.dispatch(hl.dsp.submap("reset"))
      end
    end

    local function toggle()
      ht().toggle("all")
      sync_submap()
    end

    -- Close-only, so a stale submap can never reopen the overview.
    local function close()
      if ht().is_active() then
        ht().toggle("all")
      end
      sync_submap()
    end

    hl.bind("SUPER + O", toggle)

    hl.define_submap("overview", function()
      for _, dir in ipairs({ "up", "down", "left", "right" }) do
        hl.bind(dir, function()
          if ht().is_active() then
            ht().move(dir)
          else
            sync_submap()
          end
        end)
      end
      -- Enter/Escape close onto the workspace you navigated to.
      hl.bind("return", close)
      hl.bind("escape", close)
      hl.bind("SUPER + O", toggle)
    end)

    hl.timer(sync_submap, { timeout = 150, type = "repeat" })

    hl.config({
      plugin = {
        hyprtasking = {
          layout = "grid",
          gap_size = 20,
          bg_color = 0xff141318, -- Noctalia base colour
          border_size = 2,
          -- Closing lands on the active (keyboard-selected) workspace;
          -- right-click still jumps to the one under the cursor.
          exit_on_hovered = false,
          warp_on_move_window = 1,
          drag_button = 0x110, -- left click: drag windows between workspaces
          select_button = 0x111, -- right click: jump to that workspace
          gestures = {
            enabled = true,
            open_fingers = 4, -- swipe up with four fingers, as in niri
            open_distance = 300,
            open_positive = true,
            move_fingers = 3,
            move_distance = 300,
          },
          grid = {
            rows = 3,
            cols = 1,
            layers = 4, -- 12 slots, enough for workspaces 1-10
            loop = false,
            loop_layers = true,
            gaps_use_aspect_ratio = true,
          },
        },
      },
    })
  '';
}
