# Hyprland plugins, installed through Nix: hyprpm can't build them on NixOS.
# nixpkgs builds each plugin against the same Hyprland as programs.hyprland,
# so versions always match. hyprland.lua itself stays hand/hyprmod-edited; it
# only needs `require("hyprtasking")` to pick up this file.
{ pkgs, ... }:

{
  xdg.configFile."hypr/hyprtasking.lua".text = ''
    -- Generated by Home Manager (home/hyprland.nix); edit it there.
    -- Niri-style overview: workspaces stacked in one zoomed-out column.
    hl.plugin.load("${pkgs.hyprlandPlugins.hyprtasking}/lib/libhyprtasking.so")

    hl.bind("SUPER + O", function() hl.plugin.hyprtasking.toggle("all") end)
    -- Escape closes the overview when it's open, and passes through otherwise.
    hl.bind("escape", function()
      if hl.plugin.hyprtasking.is_active() then
        hl.plugin.hyprtasking.toggle("all")
      end
    end, { non_consuming = true })

    hl.config({
      plugin = {
        hyprtasking = {
          layout = "grid",
          gap_size = 20,
          bg_color = 0xff141318, -- Noctalia base colour
          border_size = 2,
          -- Closing the overview lands on the workspace under the cursor.
          exit_on_hovered = true,
          warp_on_move_window = 1,
          drag_button = 0x110, -- left click: drag windows between workspaces
          select_button = 0x111, -- right click: jump to that workspace
          gestures = {
            enabled = true,
            open_fingers = 4, -- swipe up with four fingers, as in niri
            open_distance = 300,
            open_positive = true,
            move_fingers = 3,
            move_distance = 300,
          },
          grid = {
            rows = 3,
            cols = 1,
            layers = 4, -- 12 slots, enough for workspaces 1-10
            loop = false,
            loop_layers = true,
            gaps_use_aspect_ratio = true,
          },
        },
      },
    })
  '';
}
